DROP TABLE input_elections;

CREATE TABLE input_elections (

    state_name varchar(30),
    state varchar(4),
    congress varchar(4),
    s_upper varchar(4),
    s_lower varchar(4),
    race_type varchar(30),
    election_name varchar(60),
    voter_power float,
    cand1_name varchar(60),
    cand1_party varchar(60),
    cand1_denier boolean,
    cand1_campaign varchar(100),
    cand1_donate varchar(100),
    cand1_contact varchar(100),
    cand2_name varchar(60),
    cand2_party varchar(60),
    cand2_denier boolean,
    cand2_campaign varchar(100),
    cand2_donate varchar(100),
    cand2_contact varchar(100),
    cand3_name varchar(60),
    cand3_party varchar(60),
    cand3_denier boolean,
    cand3_campaign varchar(100),
    cand3_donate varchar(100),
    cand3_contact varchar(100),
    cand4_name varchar(60),
    cand4_party varchar(60),
    cand4_denier boolean,
    cand4_campaign varchar(100),
    cand4_donate varchar(100),
    cand4_contact varchar(100),
    cand5_name varchar(60),
    cand5_party varchar(60),
    cand5_denier boolean,
    cand5_campaign varchar(100),
    cand5_donate varchar(100),
    cand5_contact varchar(100),
    cand6_name varchar(60),
    cand6_party varchar(60),
    cand6_denier boolean,
    cand6_campaign varchar(100),
    cand6_donate varchar(100),
    cand6_contact varchar(100),
    categorical_flag varchar(60),
    numerical_flag int,
    explainer_text varchar(500),
    PRIMARY KEY (state, congress, s_upper, s_lower, race_type)
);